apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: dadrix
  labels:
    tiers: website
    name: website
spec:
  selector:
    tiers: website
    name: website
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
