apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: dadrix
  labels:
    tier: website
    app: website
spec:
  selector:
    tier: website
    app: website
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
